#!/usr/bin/env python3
"""Generate kernel/src/gui/font_data.rs: anti-aliased fonts for the desktop.

Usage: scripts/gen-aa-font.py > kernel/src/gui/font_data.rs

Each glyph is rasterised with FreeType (through Pillow) into 8-bit
coverage, so the kernel can blend smooth text without a font renderer.
Needs Pillow (pip install pillow) and the DejaVu fonts in fonts/.
"""
import sys

from PIL import ImageFont

LATIN = [(0x20, 0x7E), (0xA0, 0xFF)]
CYRILLIC = [(0x401, 0x45F)]
PUNCT = [(0x2013, 0x2014), (0x2022, 0x2022), (0x2026, 0x2026), (0x2039, 0x203A)]
BOX = [(0x2500, 0x257F), (0x2588, 0x2588), (0x2591, 0x2592)]

# (Rust name, file, pixel size, ranges)
FONTS = [
    ("UI", "fonts/DejaVuSans.ttf", 14, LATIN + CYRILLIC + PUNCT),
    ("UI_BOLD", "fonts/DejaVuSans-Bold.ttf", 14, LATIN + CYRILLIC + PUNCT),
    ("TITLE", "fonts/DejaVuSans-Bold.ttf", 20, LATIN + CYRILLIC + PUNCT),
    ("LARGE", "fonts/DejaVuSans.ttf", 34, [(0x20, 0x7E), (0xB1, 0xB1), (0xD7, 0xD7), (0xF7, 0xF7)]),
    ("HEADING", "fonts/DejaVuSans.ttf", 28, LATIN + CYRILLIC + PUNCT),
    ("CLOCK", "fonts/DejaVuSans.ttf", 128, [(0x30, 0x3A)]),
    ("MONO", "fonts/DejaVuSansMono.ttf", 15, LATIN + CYRILLIC + PUNCT + BOX),
]


def font_rs(name, path, size, ranges):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    glyphs, alpha = [], bytearray()
    for first, last in ranges:
        for code in range(first, last + 1):
            ch = chr(code)
            if code != 0x20 and font.getmask(ch).getbbox() is None and not ch.isspace():
                continue  # the font has no glyph for it
            mask, (ox, oy) = font.getmask2(ch, mode="L")
            w, h = mask.size
            box = mask.getbbox()
            data = bytes(mask)
            if box is None:
                w = h = 0
                data = b""
            else:
                # trim empty borders
                x0, y0, x1, y1 = box
                rows = [data[y * w + x0:y * w + x1] for y in range(y0, y1)]
                ox, oy = ox + x0, oy + y0
                w, h = x1 - x0, y1 - y0
                data = b"".join(rows)
            advance = round(font.getlength(ch) * 16)
            glyphs.append((code, w, h, ox, oy, advance, len(alpha)))
            alpha += data
    out = [f"pub static {name}: Font = Font {{"]
    out.append(f"    line_height: {ascent + descent},")
    out.append("    glyphs: &[")
    for g in glyphs:
        out.append("        Glyph {{ code: {}, w: {}, h: {}, x: {}, y: {}, advance: {}, offset: {} }},".format(*g))
    out.append("    ],")
    out.append("    alpha: &[")
    for i in range(0, len(alpha), 32):
        out.append("        " + ", ".join(str(b) for b in alpha[i:i + 32]) + ",")
    out.append("    ],")
    out.append("};")
    return "\n".join(out)


def main():
    print("// Generated by scripts/gen-aa-font.py from the DejaVu fonts in fonts/.")
    print("// DejaVu fonts: Bitstream Vera license, see fonts/LICENSE.dejavu.")
    print("// Do not edit by hand.")
    print()
    print("use super::text::{Font, Glyph};")
    for f in FONTS:
        print()
        print(font_rs(*f))


if __name__ == "__main__":
    sys.exit(main())
