#!/usr/bin/env python3
"""Generate kernel/src/font_data.rs from an 8x16 PSF console font.

Usage: scripts/gen-font.py fonts/Uni2-Terminus16.psf.gz > kernel/src/font_data.rs

Only the Unicode ranges in RANGES are kept, so the kernel stays small.
"""
import gzip
import struct
import sys

# (first, last) code points to include, inclusive.
RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1
    (0x0400, 0x045F),  # Cyrillic
    (0x2500, 0x257F),  # box drawing
    (0x2588, 0x2588),  # full block
    (0x2591, 0x2592),  # light and medium shade
]
WIDTH, HEIGHT = 8, 16


def parse(path):
    """Return {code point: 16 row bytes} from a PSF1 or PSF2 font."""
    data = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    if data[:2] == b"\x36\x04":  # PSF1
        mode, size = data[2], data[3]
        count = 512 if mode & 1 else 256
        offset, height, has_table = 4, size, mode & 2
        table = data[offset + count * size :]
        codes = struct.unpack(f"<{len(table) // 2}H", table[: len(table) // 2 * 2])
        records, current = [], []
        for code in codes:
            if code == 0xFFFF:  # end of this glyph's list
                records.append(current)
                current = []
            else:
                current.append(code)
        # 0xFFFE starts combining sequences, which we ignore
        records = [r[: r.index(0xFFFE)] if 0xFFFE in r else r for r in records]
    elif data[:4] == b"\x72\xb5\x4a\x86":  # PSF2
        _, _, offset, flags, count, size, height, width = struct.unpack("<8I", data[:32])
        assert width == WIDTH, "only 8 pixel wide fonts are supported"
        has_table = flags & 1
        table = data[offset + count * size :]
        records = []
        for chunk in table.split(b"\xff")[:count]:
            chunk = chunk.split(b"\xfe")[0]  # ignore combining sequences
            records.append([ord(c) for c in chunk.decode("utf-8")])
    else:
        sys.exit("not a PSF font")
    assert height == HEIGHT, "only 16 pixel high fonts are supported"
    assert has_table, "the font has no Unicode table"

    glyphs = {}
    for index, codes in enumerate(records[:count]):
        rows = list(data[offset + index * size : offset + index * size + HEIGHT])
        for code in codes:
            glyphs.setdefault(code, rows)
    return glyphs


def main():
    glyphs = parse(sys.argv[1])
    out = [
        "//! Generated by scripts/gen-font.py from Terminus Font 8x16",
        "//! (SIL Open Font License 1.1, see fonts/LICENSE.terminus).",
        "//! Do not edit by hand.",
        "",
        "/// (first code point, last code point, index of the first glyph)",
        "pub const RANGES: &[(u32, u32, usize)] = &[",
    ]
    table = []
    for first, last in RANGES:
        out.append(f"    (0x{first:04x}, 0x{last:04x}, {len(table)}),")
        for code in range(first, last + 1):
            table.append((code, glyphs.get(code, [0] * HEIGHT)))
    out.append("];")
    out.append("")
    out.append(f"pub static GLYPHS: [[u8; {HEIGHT}]; {len(table)}] = [")
    for code, rows in table:
        body = ", ".join(f"0x{r:02x}" for r in rows)
        out.append(f"    [{body}], // U+{code:04X}")
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main()
